**BEST MODEL (LINEAR KERNEL WITH C=0.1)**

In [ ]:
from keras.datasets import cifar10
import numpy as np


In [ ]:
classesName = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_val = x_train[49000:, :].astype(float) # Use float instead of np.float
y_val = np.squeeze(y_train[49000:, :])
x_train = x_train[:49000, :].astype(float) # Use float instead of np.float
y_train = np.squeeze(y_train[:49000, :])
y_test = np.squeeze(y_test)
x_test = x_test.astype(float) # Use float instead of np.float

In [ ]:
print(x_train.shape)
print(y_train.shape)
x_train = np.reshape(x_train, (x_train.shape[0], -1)) # The -1 means that the corresponding dimension is calculated from the other given dimensions.
xVal = np.reshape(x_val, (x_val.shape[0], -1))
xTest = np.reshape(x_test, (x_test.shape[0], -1))
print(x_train.shape)
print(x_train[0])

#Normalize
xTrain=((xTrain/255)*2)-1
print(xTrain.shape)
print(xTrain[0])

(49000, 3072)
(49000,)
(49000, 3072)
[ 59.  62.  63. ... 123.  92.  72.]
(50000, 32, 32, 3)
[[[-1.00421376 -1.00402922 -1.0039677 ]
  [-1.005198   -1.00501346 -1.00507497]
  [-1.0047674  -1.00489043 -1.005198  ]
  ...
  [-0.9981238  -0.99972318 -1.00119954]
  [-0.99849289 -1.00015379 -1.00156863]
  [-0.99873895 -1.0002153  -1.00150711]]

 [[-1.0068589  -1.00661284 -1.00661284]
  [-1.00784314 -1.00784314 -1.00784314]
  [-1.00673587 -1.00735102 -1.00784314]
  ...
  [-1.00027682 -1.00242983 -1.00445982]
  [-1.00052288 -1.00273741 -1.0047674 ]
  [-1.00033833 -1.00249135 -1.00433679]]

 [[-1.00630527 -1.00636678 -1.00655133]
  [-1.0068589  -1.00741253 -1.00784314]
  [-1.00482891 -1.00618224 -1.00735102]
  ...
  [-1.00058439 -1.00267589 -1.0047674 ]
  [-1.00046136 -1.00267589 -1.0047674 ]
  [-1.00113802 -1.00335256 -1.00525952]]

 ...

 [[-0.99504806 -0.99738562 -1.00193772]
  [-0.99547866 -0.99843137 -1.00575163]
  [-0.99566321 -0.99793925 -1.00624375]
  ...
  [-0.99800077 -0.99966167 -1.00

**SVM Linear Kernal with C=0.1.**

In [ ]:
x_train = x_train[:10000,:]
y_train = y_train[:10000]
print(y_train)
print(x_train.shape)
print(y_train.shape)
from sklearn import svm
svc = svm.SVC(probability = False,kernel='linear', C=0.1)
svc.fit(x_train, y_train)

[6 9 9 ... 1 1 5]
(10000, 3072)
(10000,)


SVC(C=0.1, kernel='linear')

**Train and Test accuracy of SVM Model.**

In [ ]:
Yhat_svc_linear_train = svc.predict(x_train)
acc_train = np.mean(Yhat_svc_linear_train == y_train)
print('Train Accuracy = {0:f}'.format(acc_train))

print("#=============================================")

# The x_val array needs to be reshaped
x_val = np.reshape(x_val, (x_val.shape[0], -1))
Yhat_svc_linear_test = svc.predict(x_val)
acc_test = np.mean(Yhat_svc_linear_test == y_val)
print('Test Accuracy = {0:f}'.format(acc_test))

Train Accuracy = 1.000000
#=============================================
Test Accuracy = 0.306000
